import type { ListingFinderConfig } from "@/types";

export const RENTAL_CONFIG: ListingFinderConfig = {
  listingType: "rental",
  title: "Rent Lobster",
  subtitle: "Apartment Listing Aggregator",
  priceLabel: "Max rent",
  minPriceLabel: "Min rent",
  defaultMinPrice: "",
  showNoFee: true,
  showHoa: false,
  appliedLabel: "Mark Applied",
  appliedActiveLabel: "Application Submitted",
  editableFields: [
    { key: "price", label: "Price", type: "number" },
    { key: "beds", label: "Beds", type: "number" },
    { key: "baths", label: "Baths", type: "number" },
    { key: "sqft", label: "Sq Ft", type: "number" },
    { key: "floor", label: "Floor", type: "text" },
    { key: "available_date", label: "Available", type: "text" },
    { key: "address", label: "Address", type: "text" },
    { key: "neighborhood", label: "Neighborhood", type: "text" },
    { key: "contact_name", label: "Contact Name", type: "text" },
    { key: "contact_phone", label: "Contact Phone", type: "text" },
    { key: "contact_email", label: "Contact Email", type: "text" },
    { key: "subway_minutes", label: "Min to Subway", type: "number" },
    { key: "nearest_subway", label: "Nearest Subway", type: "text" },
  ],
  amenityLabels: {
    has_dishwasher: "Dishwasher",
    has_balcony: "Balcony",
    has_doorman: "Doorman",
    has_elevator: "Elevator",
    has_gym: "Gym",
    pets_allowed: "Pets OK",
    no_fee: "No Fee",
  },
};

export const SALE_CONFIG: ListingFinderConfig = {
  listingType: "sale",
  title: "Rent Lobster",
  subtitle: "Condo & Real Estate Finder",
  priceLabel: "Max price",
  minPriceLabel: "Min price",
  // Rentals priced at $3,000-$5,000/mo occasionally show up on sale results
  // pages. A $50k floor filters them out without rejecting real cheap buys
  // (e.g. land lots or storage units would still need an explicit override).
  defaultMinPrice: "50000",
  showNoFee: false,
  showHoa: true,
  appliedLabel: "Mark Offer Made",
  appliedActiveLabel: "Offer Submitted",
  editableFields: [
    { key: "price", label: "Price", type: "number" },
    { key: "beds", label: "Beds", type: "number" },
    { key: "baths", label: "Baths", type: "number" },
    { key: "sqft", label: "Sq Ft", type: "number" },
    { key: "floor", label: "Floor", type: "text" },
    { key: "property_type", label: "Property Type", type: "text" },
    { key: "hoa_fee", label: "HOA / Mo", type: "number" },
    { key: "tax_annual", label: "Annual Tax", type: "number" },
    { key: "year_built", label: "Year Built", type: "number" },
    { key: "available_date", label: "Available", type: "text" },
    { key: "address", label: "Address", type: "text" },
    { key: "neighborhood", label: "Neighborhood", type: "text" },
    { key: "contact_name", label: "Contact Name", type: "text" },
    { key: "contact_phone", label: "Contact Phone", type: "text" },
    { key: "contact_email", label: "Contact Email", type: "text" },
    { key: "subway_minutes", label: "Min to Subway", type: "number" },
    { key: "nearest_subway", label: "Nearest Subway", type: "text" },
  ],
  amenityLabels: {
    has_dishwasher: "Dishwasher",
    has_balcony: "Balcony",
    has_doorman: "Doorman",
    has_elevator: "Elevator",
    has_gym: "Gym",
    pets_allowed: "Pets OK",
  },
};
