import type React from "react";

export const s: Record<string, React.CSSProperties> = {
  page: { minHeight: "100vh", backgroundColor: "#f8fafc" },

  /* Header */
  header: {
    background: "linear-gradient(135deg, #dc2626 0%, #991b1b 100%)",
    padding: "40px 20px",
    color: "white",
  },
  headerInner: { maxWidth: 1200, margin: "0 auto", position: "relative" as const },
  headerLogo: {
    position: "absolute" as const,
    left: -70,
    top: "50%",
    transform: "translateY(-50%)",
    width: 56,
    height: 56,
    objectFit: "contain" as const,
    borderRadius: 10,
  },
  title: { margin: 0, fontSize: 36, fontWeight: 800, letterSpacing: "-0.02em" },
  subtitle: { margin: "8px 0 0", fontSize: 16, opacity: 0.85, fontWeight: 400 },

  main: { maxWidth: 1200, margin: "0 auto", padding: "24px 20px 60px" },

  /* Crawl panel */
  crawlPanel: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: "24px 28px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
    marginBottom: 24,
  },
  sectionTitle: { margin: "0 0 16px", fontSize: 18, fontWeight: 700, color: "#111827" },
  crawlControls: {
    display: "flex",
    flexWrap: "wrap" as const,
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
  },
  spiderChecks: { display: "flex", gap: 20, flexWrap: "wrap" as const },
  crawlRight: { display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" as const },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 15,
    fontWeight: 500,
    color: "#374151",
    cursor: "pointer",
    userSelect: "none" as const,
  },
  checkbox: { width: 18, height: 18, accentColor: "#dc2626", cursor: "pointer" },
  inlineLabel: { display: "flex", alignItems: "center", gap: 8, fontSize: 14, color: "#374151" },

  /* Progress */
  progressWrap: { marginTop: 4 },
  progressTrack: {
    height: 10,
    borderRadius: 5,
    backgroundColor: "#e5e7eb",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 5,
    backgroundColor: "#dc2626",
    transition: "width 0.4s ease",
  },
  progressLabel: { marginTop: 6, fontSize: 13, color: "#6b7280" },
  crawlDone: {
    padding: "10px 14px",
    borderRadius: 8,
    backgroundColor: "#f0fdf4",
    color: "#166534",
    fontSize: 14,
    border: "1px solid #bbf7d0",
  },
  crawlError: {
    padding: "10px 14px",
    borderRadius: 8,
    backgroundColor: "#fef2f2",
    color: "#991b1b",
    fontSize: 14,
    border: "1px solid #fecaca",
  },

  /* Stats */
  statsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: 16,
    marginBottom: 24,
  },
  statCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: "20px 24px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
  },
  statValue: { fontSize: 28, fontWeight: 700, color: "#111827" },
  statLabel: {
    fontSize: 13,
    color: "#6b7280",
    marginTop: 4,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
  },

  /* Filters */
  filters: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 12,
    marginBottom: 24,
    alignItems: "center",
  },
  select: {
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid #d1d5db",
    fontSize: 14,
    backgroundColor: "white",
    minWidth: 150,
  },
  input: {
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid #d1d5db",
    fontSize: 14,
    width: 130,
  },
  button: {
    padding: "10px 20px",
    borderRadius: 8,
    border: "none",
    backgroundColor: "#dc2626",
    color: "white",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },

  /* Messages */
  errorMsg: {
    color: "#dc2626",
    backgroundColor: "#fef2f2",
    padding: "12px 16px",
    borderRadius: 8,
    border: "1px solid #fecaca",
  },
  loadingMsg: { textAlign: "center" as const, color: "#6b7280", padding: 40, fontSize: 16 },
  empty: {
    textAlign: "center" as const,
    padding: "60px 20px",
    backgroundColor: "white",
    borderRadius: 12,
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
  },

  /* View toggle */
  viewToggle: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    flexWrap: "wrap" as const,
    gap: 12,
  },
  toggleBtns: {
    display: "flex",
    gap: 0,
    borderRadius: 8,
    overflow: "hidden",
    border: "1px solid #d1d5db",
  },
  toggleBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 16px",
    border: "none",
    backgroundColor: "white",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    color: "#374151",
  },
  toggleBtnActive: {
    backgroundColor: "#dc2626",
    color: "white",
  },

  /* Results meta */
  resultsMeta: { marginBottom: 0 },

  /* Grid & Cards */
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))",
    gap: 16,
  },
  card: {
    display: "flex",
    flexDirection: "column" as const,
    backgroundColor: "white",
    borderRadius: 12,
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
    overflow: "hidden",
    textDecoration: "none",
    color: "inherit",
    transition: "transform 0.15s, box-shadow 0.15s",
    cursor: "pointer",
  },
  cardOverlay: {
    position: "absolute" as const,
    top: 8,
    right: 8,
    zIndex: 2,
  },
  noFeeBadge: {
    position: "absolute" as const,
    top: 8,
    left: 8,
    backgroundColor: "#16a34a",
    color: "white",
    padding: "3px 8px",
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.02em",
    zIndex: 2,
  },
  thumbImg: {
    width: "100%",
    height: 180,
    objectFit: "cover" as const,
    display: "block",
  },
  thumbPlaceholder: {
    width: "100%",
    height: 120,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f1f5f9",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 20px 0",
  },
  badge: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 20,
    fontSize: 12,
    fontWeight: 600,
    color: "white",
    textTransform: "capitalize" as const,
  },
  statusDot: {
    display: "inline-block",
    width: 10,
    height: 10,
    borderRadius: "50%",
    flexShrink: 0,
  },
  price: { fontSize: 22, fontWeight: 700, color: "#111827" },
  cardBody: { padding: "10px 20px", flex: 1 },
  address: {
    margin: "0 0 4px",
    fontSize: 15,
    fontWeight: 500,
    color: "#1f2937",
    lineHeight: 1.4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  neighborhood: { margin: "0 0 8px", fontSize: 13, color: "#6b7280" },
  details: { display: "flex", gap: 12, flexWrap: "wrap" as const },
  detail: {
    fontSize: 13,
    color: "#374151",
    backgroundColor: "#f3f4f6",
    padding: "3px 8px",
    borderRadius: 6,
  },
  chipRow: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap" as const,
    marginTop: 8,
  },
  chip: {
    fontSize: 11,
    color: "#0369a1",
    backgroundColor: "#e0f2fe",
    padding: "2px 7px",
    borderRadius: 4,
    fontWeight: 500,
  },
  cardFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 20px",
    borderTop: "1px solid #f3f4f6",
    fontSize: 13,
    color: "#9ca3af",
  },
  linkText: { color: "#dc2626", fontWeight: 500 },

  /* Star */
  starBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
  },

  /* Pagination */
  pagination: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    marginTop: 32,
  },
  pageBtn: {
    padding: "8px 14px",
    borderRadius: 8,
    border: "1px solid #d1d5db",
    backgroundColor: "white",
    fontSize: 14,
    cursor: "pointer",
    color: "#374151",
    fontWeight: 500,
  },
  pageBtnActive: {
    backgroundColor: "#dc2626",
    color: "white",
    borderColor: "#dc2626",
  },
  pageEllipsis: {
    padding: "8px 6px",
    color: "#9ca3af",
    fontSize: 14,
  },

  /* Modal */
  modalOverlay: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: 20,
  },
  modalCard: {
    backgroundColor: "white",
    borderRadius: 16,
    width: "100%",
    maxWidth: 700,
    maxHeight: "90vh",
    overflow: "auto" as const,
    position: "relative" as const,
    boxShadow: "0 25px 50px rgba(0,0,0,0.25)",
  },
  modalClose: {
    position: "absolute" as const,
    top: 12,
    right: 16,
    background: "rgba(0,0,0,0.5)",
    border: "none",
    color: "white",
    fontSize: 28,
    cursor: "pointer",
    width: 36,
    height: 36,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
    lineHeight: 1,
  },
  modalImgWrap: {
    width: "100%",
    maxHeight: 300,
    overflow: "hidden",
  },
  galleryWrap: {
    position: "relative" as const,
    width: "100%",
    maxHeight: 400,
    overflow: "hidden",
    backgroundColor: "#0f172a",
  },
  galleryImg: {
    width: "100%",
    height: 400,
    objectFit: "contain" as const,
    display: "block",
  },
  galleryArrow: {
    position: "absolute" as const,
    top: "50%",
    transform: "translateY(-50%)",
    width: 40,
    height: 40,
    borderRadius: "50%",
    border: "none",
    backgroundColor: "rgba(0,0,0,0.55)",
    color: "white",
    fontSize: 20,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 5,
    transition: "background-color 0.15s",
  },
  galleryArrowLeft: {
    left: 12,
  },
  galleryArrowRight: {
    right: 12,
  },
  galleryCounter: {
    position: "absolute" as const,
    bottom: 12,
    right: 14,
    backgroundColor: "rgba(0,0,0,0.6)",
    color: "white",
    fontSize: 12,
    fontWeight: 600,
    padding: "4px 10px",
    borderRadius: 12,
    zIndex: 5,
  },
  galleryDots: {
    position: "absolute" as const,
    bottom: 12,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    gap: 6,
    zIndex: 5,
  },
  galleryDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    backgroundColor: "rgba(255,255,255,0.45)",
    border: "none",
    padding: 0,
    cursor: "pointer",
    transition: "background-color 0.15s",
  },
  galleryDotActive: {
    backgroundColor: "white",
  },
  modalHeader: {
    padding: "20px 24px 0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap" as const,
    gap: 12,
  },
  modalBody: {
    padding: "16px 24px 24px",
  },
  modalActions: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap" as const,
    marginBottom: 20,
  },
  actionBtn: {
    padding: "8px 16px",
    borderRadius: 8,
    border: "1px solid #d1d5db",
    backgroundColor: "white",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    color: "#374151",
  },
  actionBtnActive: {
    backgroundColor: "#eab308",
    color: "white",
    borderColor: "#eab308",
  },
  actionBtnLink: {
    padding: "8px 16px",
    borderRadius: 8,
    border: "1px solid #dc2626",
    backgroundColor: "white",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    color: "#dc2626",
    textDecoration: "none",
  },
  modalSection: {
    marginBottom: 20,
  },
  modalSectionTitle: {
    margin: "0 0 10px",
    fontSize: 15,
    fontWeight: 700,
    color: "#111827",
    borderBottom: "1px solid #f3f4f6",
    paddingBottom: 6,
  },

  /* Editable fields */
  editFieldGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "6px 16px",
  },
  editFieldRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "4px 0",
    minHeight: 32,
  },
  editFieldLabel: {
    fontSize: 13,
    color: "#6b7280",
    fontWeight: 500,
    flexShrink: 0,
    marginRight: 8,
  },
  editFieldValue: {
    fontSize: 14,
    color: "#111827",
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  editFieldInput: {
    padding: "4px 8px",
    borderRadius: 6,
    border: "1px solid #93c5fd",
    fontSize: 14,
    width: 120,
    outline: "none",
  },
  editPencilBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "#9ca3af",
    padding: 2,
    display: "inline-flex",
    alignItems: "center",
    flexShrink: 0,
  },

  /* Amenities */
  amenityGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "6px 16px",
  },
  amenityCheckLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 14,
    color: "#374151",
    cursor: "pointer",
  },

  /* Description */
  descriptionText: {
    fontSize: 14,
    color: "#374151",
    lineHeight: 1.6,
    margin: 0,
    whiteSpace: "pre-wrap" as const,
    maxHeight: 200,
    overflow: "auto" as const,
  },

  /* Notes */
  notesArea: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid #d1d5db",
    fontSize: 14,
    resize: "vertical" as const,
    fontFamily: "inherit",
    lineHeight: 1.5,
    boxSizing: "border-box" as const,
  },
};
